#!/usr/bin/env bats
# merge-pr-quality-step.bats — the PR quality profile still has a home in
# commands/merge-pr.md, and every stop-worthy exit is still named explicitly,
# so an agent following the command halts on a policy failure, unavailable
# tooling, or a missing binary instead of reading past the numbers.
#
# What changed (P-G1): the quality verdict is produced at `local-attest`,
# pinned to the head SHA, and CONSUMED by the merge gate. merge-pr runs the
# profile itself only on the explicit path — a repository whose base ref has
# not enabled attestation enforcement. KD-9 still holds ("the merge gate reads
# that verdict"); it is only now literally true, because before this the
# command ran the check and the gate never saw the result.
#
# These assertions therefore pin the EXPLICIT path. merge-pr-attestation.bats
# pins the other half: that the attested path does not run it at all.
#
# Checked in all three shipped copies. They are not equally exposed, and the
# redundancy is deliberate:
#   - commands/merge-pr.md is the source.
#   - templates/claude/commands/merge-pr.md is generated from it and already
#     held to byte-equality by `build-plugin --check` (dogfood.yml:42), so
#     this case is defence-in-depth, not the enforcement seam — do not
#     hand-edit that template on the strength of this test passing.
#   - .github/prompts/merge-pr.prompt.md is generated by project-sync but is
#     NOT gated in CI (dogfood never runs check-project-sync, and doctor
#     downgrades a stale prompt to a warning), so that case is load-bearing.

load helpers

check_quality_step() {
  local file="$1"

  run grep -F "dotbabel quality check --profile pr" "$file"
  [ "$status" -eq 0 ]

  run grep -i "exit code \`1\` means a checked rule failed" "$file"
  [ "$status" -eq 0 ]

  run grep -i "exit code \`2\` means required evidence" "$file"
  [ "$status" -eq 0 ]

  # "STOP" is markdown-bolded (**STOP**) in the prose, so match past the
  # markers rather than the literal word plus a space.
  run grep -i "STOP.*for either exit code" "$file"
  [ "$status" -eq 0 ]

  # Every other non-zero exit must stop too. Leaving 127 (dotbabel absent on
  # the bootstrap-only install path) and 64 (usage) unnamed is what lets an
  # agent read "not 1, not 2" as "carry on" and merge with no gate at all.
  # Regex, not -F: the prose backticks each exit code (`127`), and a literal
  # pattern would have to embed them exactly. `.*` spans them instead.
  run grep -i "127.*not installed" "$file"
  [ "$status" -eq 0 ]
  run grep -i "64.*invalid usage" "$file"
  [ "$status" -eq 0 ]
  run grep -i "never report an unrun gate as a pass" "$file"
  [ "$status" -eq 0 ]

  # The throwaway worktree can never match the trust allowlist, so exit 2 is
  # the expected first result. The step must say so and must not send the
  # operator to a blanket --allow-project-commands.
  run grep -i "Expect exit \`2\` on the first run" "$file"
  [ "$status" -eq 0 ]
  run grep -i "Do not reach for a blanket" "$file"
  [ "$status" -eq 0 ]

  # The removed gate must not still be described anywhere in the step.
  run grep -i "regression" "$file"
  [ "$status" -eq 1 ]
}

@test "merge-pr: the explicit path runs the PR quality profile and stops on exit 1 or 2" {
  check_quality_step "$REPO_ROOT/commands/merge-pr.md"
}

@test "merge-pr template copy: the explicit path runs the PR quality profile and stops on exit 1 or 2" {
  check_quality_step "$REPO_ROOT/plugins/dotbabel/templates/claude/commands/merge-pr.md"
}

@test "merge-pr prompt copy: the explicit path runs the PR quality profile and stops on exit 1 or 2" {
  check_quality_step "$REPO_ROOT/.github/prompts/merge-pr.prompt.md"
}
