/**
 * model-intelligence/requirement/schema — the single authority for the shape of
 * a `dotbabel.compute` declaration (docs/specs/model-intelligence, §5).
 *
 * `MODE_RULES` states each resolution mode's conditional rules once. The parser
 * in `./index.mjs` reads that table, and `buildComputeSchema()` renders the same
 * table into the JSON Schema that `schemas/dotbabel.compute.schema.json` holds.
 * `scripts/build-compute-schema.mjs` writes that file and its `--check` mode
 * fails when the file and this table disagree, so a new mode is one edit here
 * rather than five edits across a schema, a parser, and their tests.
 *
 * Pure: no I/O, no clock, no environment (ARCH-56). The enums come from the
 * domain vocabulary and are never redeclared as literals (ARCH-58).
 */

import {
  BINDINGS,
  COMPUTE_SCHEMA_ID,
  RESOLUTION_MODES,
  RUNTIME_IDS,
  WORKLOAD_CLASSES,
} from "../domain/index.mjs";

/**
 * @typedef {object} ModeRule
 * @property {boolean} requirement Whether `requirement` must be present.
 * @property {boolean} pin Whether `pin` must be present.
 * @property {string} why One-line reason, rendered into the schema description.
 */

/**
 * Conditional rules per resolution mode. `requirement: false` and `pin: false`
 * mean the field is forbidden, not merely optional: §5 states every mode's
 * requirement either way, so there is no third state to express.
 * @type {Readonly<Record<string, ModeRule>>}
 */
export const MODE_RULES = Object.freeze({
  dynamic: Object.freeze({
    requirement: true,
    pin: false,
    why: "resolve the semantic requirement against current usable capability evidence",
  }),
  floor: Object.freeze({
    requirement: true,
    pin: false,
    why: "treat the requirement as a minimum capability bound",
  }),
  pin: Object.freeze({
    requirement: true,
    pin: true,
    why: "require one exact runtime-native configuration, and record why it exists",
  }),
  inherit: Object.freeze({
    requirement: false,
    pin: false,
    why: "introduce no requirement of this artifact's own",
  }),
});

/** Keys that `dotbabel.compute` accepts in v1. */
export const COMPUTE_KEYS = Object.freeze(["requirement", "binding", "mode", "pin", "rationale"]);

/** Keys that `pin` accepts. */
export const PIN_KEYS = Object.freeze(["runtime", "config"]);

/**
 * Render one mode's rule as a JSON Schema `if`/`then` clause.
 * @param {string} mode
 * @param {ModeRule} rule
 * @returns {object}
 */
function modeClause(mode, rule) {
  /** @type {string[]} */
  const required = [];
  /** @type {string[]} */
  const forbidden = [];
  for (const field of ["requirement", "pin"]) {
    if (rule[field]) required.push(field);
    else forbidden.push(field);
  }
  /** @type {Record<string, unknown>} */
  const then = {};
  if (required.length > 0) then.required = required;
  if (forbidden.length === 1) then.not = { required: forbidden };
  else if (forbidden.length > 1) then.not = { anyOf: forbidden.map((field) => ({ required: [field] })) };
  return {
    if: { properties: { mode: { const: mode } }, required: ["mode"] },
    then,
  };
}

/**
 * Build the JSON Schema for the `dotbabel` frontmatter namespace.
 *
 * The `dotbabel` object itself stays open so a later unit can add a sibling of
 * `compute`. `compute` is closed, so a misspelled key is an error rather than
 * inert policy (§5, "Strictness").
 * @returns {object} A fresh, mutable schema document, ready to serialise.
 */
export function buildComputeSchema() {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: COMPUTE_SCHEMA_ID,
    title: "dotbabel namespace: compute requirement",
    description:
      "The canonical, provider-neutral compute requirement of a Dotbabel artifact (spec model-intelligence, KD-1). Generated by scripts/build-compute-schema.mjs from MODE_RULES and the domain vocabulary — edit that table, not this file.",
    type: "object",
    additionalProperties: true,
    properties: {
      compute: {
        type: "object",
        additionalProperties: false,
        required: ["binding", "mode"],
        properties: {
          requirement: {
            description:
              "Semantic workload class, ordered by required reasoning capability. Not a model score.",
            type: "string",
            enum: [...WORKLOAD_CLASSES],
          },
          binding: {
            description:
              "Where the requirement applies: `self` owns a compute context, `session` applies to the coordinator session, `consumer` applies to the context consuming the artifact.",
            type: "string",
            enum: [...BINDINGS],
          },
          mode: {
            description: Object.entries(MODE_RULES)
              .map(([mode, rule]) => `\`${mode}\`: ${rule.why}.`)
              .join(" "),
            type: "string",
            enum: [...RESOLUTION_MODES],
          },
          pin: {
            description: "One exact runtime-native configuration. Only for `mode: pin`.",
            type: "object",
            additionalProperties: false,
            required: [...PIN_KEYS],
            properties: {
              runtime: {
                description:
                  "A runtime id of the dotbabel runtime registry. A runtime is an execution harness, not a model vendor.",
                type: "string",
                enum: [...RUNTIME_IDS],
              },
              config: {
                description:
                  "Opaque runtime-native configuration. Dotbabel does not assume that every runtime has a model and an effort axis, and it never derives meaning from the spelling of an identifier.",
                type: "object",
                minProperties: 1,
              },
            },
          },
          rationale: {
            description: "Human-readable reason for the requirement.",
            type: "string",
          },
        },
        allOf: Object.entries(MODE_RULES).map(([mode, rule]) => modeClause(mode, rule)),
      },
    },
  };
}
