// Additive boundary tests for `quality/discovery.mjs`, which the TEST-1
// mutation run left at 84.57% (#390). Fixture helpers mirror
// quality-discovery.test.mjs.
//
// These mutants are equivalent and are not chased:
//   - 10:61, 154:58: the `paths` and `includeTests` defaults. Every caller
//     passes the argument.
//   - 61:51, 67:106, 73:52, 82:95, 92:79: `?? []` fallbacks replaced with
//     `["Stryker was here"]`. A string item has no `.path`, `criticalMatches`
//     is always set by `planQualityCheck` before `applyPathTriggers` runs, and
//     the other lists only match a file or glob with that literal name.
//   - 55:66: the `patterns` default. The literal glob matches only a file with
//     that literal name.
//   - 41:112 (`$` removed from the comment-strip regex): with the `m` flag,
//     `.*` already stops at the end of the line.
//   - 49:11: `hasTsCheck`'s `catch` returning undefined instead of false. The
//     only caller uses the value as a boolean.
//   - 113:12, 128:56, 144:71: every component file is filtered again by
//     `nearestRoot`, which only returns a component whose root holds the
//     file, and every plan names a component from the same detection.
//   - 123:84 (`item.root === component.root` forced true): a discovered
//     tsconfig also yields a JavaScript component at the same root, and
//     `nearestRoot` gives it the root's files first. Only a hand-declared
//     TypeScript root with no same-root JavaScript component differs, and
//     there the file's double ownership is not a contract to pin.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

import {
  detectQualityCapabilities,
  filesMatchingQualityPaths,
  planQualityCheck,
  qualityChangePaths,
} from "../src/quality/discovery.mjs";

const dirs = [];
function tempRepo(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "dotbabel-quality-discovery-behavior-"));
  dirs.push(dir);
  for (const [name, body] of Object.entries(files)) {
    fs.mkdirSync(path.dirname(path.join(dir, name)), { recursive: true });
    fs.writeFileSync(path.join(dir, name), body);
  }
  return dir;
}
afterEach(() => {
  vi.unstubAllEnvs();
  dirs.splice(0).forEach((dir) => fs.rmSync(dir, { recursive: true, force: true }));
});

const filesOf = (result, id) => result.components.find((item) => item.id === id).files;
const rust = (root, tools = {}) => ({ root, languages: ["rust"], tools });

describe("quality discovery exclusions", () => {
  it("excludes a generated header with several words between the markers", () => {
    const repoRoot = tempRepo({ "src/pb.js": "// Code generated by protoc-gen-go. DO NOT EDIT.\n", "src/live.js": "export {};\n" });
    const result = detectQualityCapabilities({ repoRoot });
    expect(result.files).toEqual(["src/live.js"]);
    expect(result.exclusions).toEqual([{ reason: "generated marker", count: 1 }]);
  });

  it("sorts exclusion reasons by name, not by the first file that hit them", () => {
    const repoRoot = tempRepo({ "a/skip.js": "export {};\n", "b/gen.js": "// @generated\n" });
    const result = detectQualityCapabilities({ repoRoot, policy: { exclude: ["a/**"] } });
    expect(result.exclusions).toEqual([
      { reason: "generated marker", count: 1 },
      { reason: "policy pattern a/**", count: 1 },
    ]);
  });
});

describe("quality discovery components", () => {
  it("gives a single-file component the file its root names", () => {
    const repoRoot = tempRepo({ "main.rs": "fn main() {}\n", "other.rs": "fn other() {}\n" });
    const result = detectQualityCapabilities({ repoRoot, policy: { components: [rust("main.rs")] } });
    expect(filesOf(result, "main.rs:rust")).toEqual(["main.rs"]);
  });

  it("sorts components by id, not by declaration order", () => {
    const repoRoot = tempRepo({ "zeta/a.rs": "fn z() {}\n", "alpha/a.rs": "fn a() {}\n" });
    const result = detectQualityCapabilities({ repoRoot, policy: { components: [rust("zeta"), rust("alpha")] } });
    expect(result.components.map((item) => item.id)).toEqual(["alpha:rust", "zeta:rust"]);
  });

  it("marks an unknown-language component checked only for an exit-code or dotbabel-v1 tool", () => {
    const repoRoot = tempRepo({ "a/x.rs": "", "b/x.rs": "", "c/x.rs": "" });
    const result = detectQualityCapabilities({ repoRoot, policy: { components: [
      rust("a", { lint: { argv: ["cargo", "clippy"] } }),
      rust("b", { lint: { argv: ["cargo", "clippy"], report: { format: "dotbabel-v1", path: "r.json" } } }),
      rust("c", { lint: { argv: ["cargo", "clippy"], report: { format: "sarif", path: "r.sarif" } } }),
    ] } });
    expect(result.components.map((item) => `${item.id}=${item.state}`)).toEqual([
      "a:rust=checked",
      "b:rust=checked",
      "c:rust=unsupported",
    ]);
  });

  it("reports the trust state of the repository it detected", () => {
    const repoRoot = tempRepo({ "src/x.rs": "" });
    const trustFile = path.join(repoRoot, "trusted");
    fs.writeFileSync(trustFile, `${repoRoot}\n`);
    vi.stubEnv("CHECK_ON_STOP_TRUSTED_FILE", trustFile);
    vi.stubEnv("CHECK_ON_STOP_TRUST_ALL", "");
    const result = detectQualityCapabilities({ repoRoot });
    expect(result.trust).toMatchObject({ trusted: true, matchedEntry: repoRoot });
    expect(result.rejectedCandidates).toEqual([]);
  });
});

describe("quality discovery TypeScript ownership", () => {
  const plainTs = { "src/value.ts": "export const value = 1;\n", "src/plain.js": "export const plain = 1;\n" };

  it("strips indented comments without touching // inside a string value", () => {
    const repoRoot = tempRepo({
      ...plainTs,
      "tsconfig.json": "{\n\"compilerOptions\": {\n    // indented comment\n\"baseUrl\":\"http://example.com\",\n\"allowJs\": true\n}\n}\n",
    });
    expect(filesOf(detectQualityCapabilities({ repoRoot }), ".:typescript")).toContain("src/plain.js");
  });

  it("owns plain JavaScript under checkJs alone", () => {
    const repoRoot = tempRepo({ ...plainTs, "tsconfig.json": JSON.stringify({ compilerOptions: { checkJs: true } }) });
    expect(filesOf(detectQualityCapabilities({ repoRoot }), ".:typescript")).toContain("src/plain.js");
  });

  it("treats an unparseable tsconfig as no compiler options", () => {
    const repoRoot = tempRepo({ ...plainTs, "tsconfig.json": "{" });
    expect(filesOf(detectQualityCapabilities({ repoRoot }), ".:typescript")).not.toContain("src/plain.js");
  });

  it("accepts an indented or unspaced @ts-check only in the first five lines", () => {
    const repoRoot = tempRepo({
      "tsconfig.json": JSON.stringify({ compilerOptions: { allowJs: false } }),
      "src/value.ts": "export const value = 1;\n",
      "src/indented.js": "  // @ts-check\nexport const a = 1;\n",
      "src/tight.js": "//@ts-check\nexport const b = 1;\n",
      "src/late.js": "\n\n\n\n\n// @ts-check\nexport const c = 1;\n",
      "src/plain.mjs": "export default 1;\n",
    });
    const files = filesOf(detectQualityCapabilities({ repoRoot }), ".:typescript");
    expect(files).toEqual(expect.arrayContaining(["src/indented.js", "src/tight.js"]));
    expect(files).not.toContain("src/late.js");
    expect(files).not.toContain("src/plain.mjs");
  });

  it("does not claim an unreadable JavaScript file for TypeScript", () => {
    const repoRoot = tempRepo({
      "tsconfig.json": JSON.stringify({ compilerOptions: { allowJs: false } }),
      "src/value.ts": "export const value = 1;\n",
    });
    execFileSync("git", ["-C", repoRoot, "init", "-q"]);
    fs.symlinkSync(path.join(repoRoot, "missing.js"), path.join(repoRoot, "src/ghost.js"));
    const result = detectQualityCapabilities({ repoRoot });
    expect(result.files).toContain("src/ghost.js");
    expect(filesOf(result, ".:typescript")).not.toContain("src/ghost.js");
  });

  it("leaves a source map with the same-root JavaScript component", () => {
    const repoRoot = tempRepo({
      "package.json": "{}\n",
      "tsconfig.json": JSON.stringify({ compilerOptions: { allowJs: true } }),
      "src/plain.js": "export default 1;\n",
      "src/plain.js.map": "{}\n",
    });
    const javascript = filesOf(detectQualityCapabilities({ repoRoot }), ".:javascript");
    expect(javascript).toContain("src/plain.js.map");
    expect(javascript).not.toContain("src/plain.js");
  });
});

describe("quality discovery path helpers", () => {
  it("matches nothing when no file list is given", () => {
    expect(filesMatchingQualityPaths(undefined, ["**"])).toEqual([]);
  });

  it("normalizes a Windows separator in a glob", () => {
    expect(filesMatchingQualityPaths(["src/a.js", "srca.js"], ["src\\a.js"])).toEqual(["src/a.js"]);
  });

  it("returns each current and previous path once, without a missing oldPath", () => {
    expect(qualityChangePaths([{ path: "a.js" }, { path: "b.js", oldPath: "a.js" }])).toEqual(["a.js", "b.js"]);
  });
});

describe("quality discovery plans", () => {
  const triggered = rust(".", {
    test: { argv: ["cargo", "test"], paths: ["tests/**"] },
    lint: { argv: ["cargo", "clippy"], paths: ["src/**", "lib/**"] },
  });
  const availability = (planned) => Object.fromEntries(planned.plans.map((plan) => [plan.capability, plan.availability]));

  it("does not trigger a path-scoped test without a critical match", () => {
    const repoRoot = tempRepo({ "docs/x.md": "" });
    const planned = planQualityCheck({ repoRoot, policy: { components: [triggered] }, profile: "pr", changeSet: { changedFiles: [{ path: "docs/x.md" }] } });
    expect(availability(planned)).toEqual({ test: "not_triggered", lint: "not_triggered" });
    expect(planned.plans.find((plan) => plan.capability === "lint").evidence).toBe("changed files did not match: src/**, lib/**");
  });

  it("forces only the test tool on a critical match", () => {
    const repoRoot = tempRepo({ "docs/x.md": "" });
    const policy = { critical_paths: ["docs/**"], components: [triggered] };
    const planned = planQualityCheck({ repoRoot, policy, profile: "pr", changeSet: { changedFiles: [{ path: "docs/x.md" }] } });
    expect(availability(planned)).toEqual({ test: "available", lint: "not_triggered" });
  });

  it("adds a generic test tool to the fast profile on a critical match without a path filter", () => {
    const repoRoot = tempRepo({ "src/x.rs": "" });
    const policy = { critical_paths: ["src/**"], components: [rust(".", { test: { argv: ["cargo", "test"] } })] };
    const planned = planQualityCheck({ repoRoot, policy, profile: "fast", changeSet: { changedFiles: [{ path: "src/x.rs" }] } });
    expect(planned.plans.map((plan) => plan.id)).toEqual([".:rust:test"]);
  });

  it("keeps plans for a component with no files when there is no path filter", () => {
    const repoRoot = tempRepo({ "src/x.rs": "" });
    const policy = { components: [rust("empty", { lint: { argv: ["cargo", "clippy"] } })] };
    const planned = planQualityCheck({ repoRoot, policy, profile: "fast", changeSet: { changedFiles: [] } });
    expect(planned.plans.map((plan) => plan.id)).toEqual(["empty:rust:lint"]);
  });

  it("stays inside the path filter when no changed file is critical", () => {
    const repoRoot = tempRepo({
      "api/go.mod": "module example.com/api\n",
      "api/main.go": "package main\n",
      "web/package.json": JSON.stringify({ scripts: { test: "node --test" } }),
      "web/index.js": "export const web = 1;\n",
    });
    const planned = planQualityCheck({ repoRoot, policy: {}, profile: "pr", paths: ["api"], changeSet: { changedFiles: [{ path: "api/main.go" }] } });
    expect(planned.components.map((item) => item.id)).not.toContain("web:javascript");
    expect(planned.plans.every((plan) => plan.componentId.startsWith("api"))).toBe(true);
  });

  it("keeps a supplied detection's components when no path filter is given", () => {
    const repoRoot = tempRepo({
      "api/go.mod": "module example.com/api\n",
      "api/main.go": "package main\n",
      "web/package.json": "{}\n",
      "web/index.js": "export const web = 1;\n",
    });
    const policy = { critical_paths: ["api/**"] };
    const detection = detectQualityCapabilities({ repoRoot, policy, paths: ["api"] });
    const planned = planQualityCheck({ repoRoot, policy, profile: "fast", detection, changeSet: { changedFiles: [{ path: "api/main.go" }] } });
    expect(planned.components.map((item) => item.id)).toEqual(detection.components.map((item) => item.id));
  });
});
